let adminState=getSite();
let selectedProductId=null,selectedCollectionId=null,selectedInterfaceLocale=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=p=>(crypto.randomUUID?crypto.randomUUID():`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`);
const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'item';
function orders(){try{return JSON.parse(localStorage.getItem(ZB_ORDERS)||'[]')}catch{return[]}}
function subs(){try{return JSON.parse(localStorage.getItem(ZB_SUBS)||'[]')}catch{return[]}}
function invoices(){try{return JSON.parse(localStorage.getItem(ZB_INVOICES)||'[]')}catch{return[]}}

function panelNav(){
  document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel,b.textContent.trim())));
  document.addEventListener('click',e=>{const j=e.target.closest('[data-jump-panel]');if(j){const b=document.querySelector(`[data-panel="${j.dataset.jumpPanel}"]`);if(b)b.click()}})
}
function openPanel(name,title){
  captureAll();
  document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));
  document.querySelectorAll('.admin-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${name}`));
  if($('adminPageTitle'))$('adminPageTitle').textContent=title||name;
  if(name==='products')renderProductList();if(name==='collections')renderCollectionList();if(name==='bundles')renderBundleEditors();if(name==='analytics')renderAnalytics();if(name==='emails')renderEmailLog();
  window.scrollTo({top:0,behavior:'smooth'});
}

function paidOrders(){return orders().filter(o=>!String(o.payment||'').toLowerCase().includes('refund'))}
function renderSales(){
  const os=paidOrders(),rev=os.reduce((sum,o)=>sum+Number(o.total||0),0);
  $('kpiRevenue').textContent=money(rev);$('kpiOrders').textContent=os.length;$('kpiAov').textContent=money(os.length?rev/os.length:0);$('kpiCustomers').textContent=new Set(os.map(o=>String(o.email||'').toLowerCase()).filter(Boolean)).size;
  const row=o=>`<tr><td><strong>${esc(o.id)}</strong></td><td>${new Date(o.date).toLocaleDateString()}</td><td>${esc(o.customer)}</td><td>${esc(o.email)}</td><td>${money(o.total)}</td><td><span class="status-pill success">${esc(o.payment)}</span></td><td>${esc(o.fulfilment)}</td></tr>`;
  $('recentOrders').innerHTML=os.slice(0,6).map(row).join('')||'<tr><td colspan="7" class="empty-cell">No orders yet.</td></tr>';
  $('ordersTable').innerHTML=orders().map((o,i)=>{const shipped=String(o.fulfilment||'').toLowerCase()==='shipped';const tracking=o.trackingNumber?`<div class="tracking-cell"><strong>${esc(o.trackingCarrier||'Carrier')}</strong><small>${esc(o.trackingNumber)}</small>${o.trackingUrl?`<a class="tracking-link" href="${esc(o.trackingUrl)}" target="_blank" rel="noopener">Track ↗</a>`:''}</div>`:'—';return `<tr><td><strong>${esc(o.id)}</strong></td><td>${new Date(o.date).toLocaleDateString()}</td><td>${esc(o.customer)}</td><td>${esc(o.email)}</td><td>${esc(o.discountCode||'—')}</td><td>${money(o.total)}</td><td>${esc(o.payment)}</td><td><span class="status-pill ${shipped?'shipped':''}">${esc(o.fulfilment||'Unfulfilled')}</span></td><td>${tracking}</td><td><button class="admin-secondary compact" data-ship-order="${i}">${shipped?'Edit shipment':'Ship order'}</button></td></tr>`}).join('')||'<tr><td colspan="10" class="empty-cell">No orders yet.</td></tr>';
  const map={};os.forEach(o=>{if(!o.email)return;const key=String(o.email).toLowerCase();if(!map[key])map[key]={name:o.customer,email:o.email,orders:0,total:0,registered:false};map[key].orders++;map[key].total+=Number(o.total||0)});getCustomers().forEach(c=>{const key=String(c.email||'').toLowerCase();if(!key)return;if(!map[key])map[key]={name:c.name,email:c.email,orders:0,total:0,registered:true};map[key].registered=true;map[key].name=map[key].name||c.name});
  $('customerList').innerHTML=Object.values(map).map(c=>`<div class="customer-row"><div class="customer-avatar">${esc((c.name||c.email||'?').slice(0,1).toUpperCase())}</div><div><strong>${esc(c.name||'Customer')}</strong><p>${esc(c.email)} · ${c.registered?'Registered account':'Guest checkout'}</p></div><div class="customer-stats"><span>${c.orders} order${c.orders===1?'':'s'}</span><strong>${money(c.total)}</strong></div></div>`).join('')||'<p class="empty-copy">No customers yet.</p>';
}
function renderAnalytics(){
  const os=paidOrders(),now=new Date(),thisY=now.getFullYear(),thisM=now.getMonth();
  const monthOrders=os.filter(o=>{const d=new Date(o.date);return d.getFullYear()===thisY&&d.getMonth()===thisM});
  const allSales=os.reduce((a,o)=>a+Number(o.total||0),0),monthSales=monthOrders.reduce((a,o)=>a+Number(o.total||0),0);
  $('analyticsMonthSales').textContent=money(monthSales);$('analyticsAllSales').textContent=money(allSales);$('analyticsMonthOrders').textContent=monthOrders.length;$('analyticsAov').textContent=money(os.length?allSales/os.length:0);$('analyticsMonthLabel').textContent=now.toLocaleDateString('en-HK',{month:'long',year:'numeric'});
  const months=[];for(let i=11;i>=0;i--){const d=new Date(thisY,thisM-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;months.push({key,label:d.toLocaleDateString('en-HK',{month:'short'}),full:d.toLocaleDateString('en-HK',{month:'long',year:'numeric'}),sales:0,orders:0})}const mm=Object.fromEntries(months.map(x=>[x.key,x]));os.forEach(o=>{const d=new Date(o.date),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(mm[k]){mm[k].sales+=Number(o.total||0);mm[k].orders++}});const max=Math.max(1,...months.map(x=>x.sales));
  $('monthlySalesChart').innerHTML=months.map(x=>`<div class="month-bar-wrap" title="${esc(x.full)}: ${money(x.sales)}"><div class="month-bar-value">${x.sales?money(x.sales):''}</div><div class="month-bar-track"><i style="height:${Math.max(x.sales?8:2,Math.round(x.sales/max*100))}%"></i></div><span>${x.label}</span></div>`).join('');
  $('monthlySalesTable').innerHTML=[...months].reverse().map(x=>`<tr><td>${esc(x.full)}</td><td>${x.orders}</td><td><strong>${money(x.sales)}</strong></td></tr>`).join('');
  const pmap={},vmap={};os.forEach(o=>(o.items||[]).forEach(item=>{const packQty=Math.max(1,Number(item.bundleQty||1)),qty=Math.max(1,Number(item.qty||1))*packQty,revenue=Number(item.price||0)*Math.max(1,Number(item.qty||1));const prod=(adminState.catalogProducts||[]).find(p=>p.id===item.productId),pname=prod?.title||String(item.name||'Product').split(' — ')[0];const variant=prod?.variants?.find(v=>v.id===item.variantId),vname=variant?.name||(String(item.name||'').includes(' — ')?String(item.name).split(' — ').slice(1).join(' — '):'Default');const pk=item.productId||pname;if(!pmap[pk])pmap[pk]={name:pname,units:0,revenue:0};pmap[pk].units+=qty;pmap[pk].revenue+=revenue;const vk=`${pk}::${item.variantId||vname}`;if(!vmap[vk])vmap[vk]={product:pname,name:vname,units:0,revenue:0};vmap[vk].units+=qty;vmap[vk].revenue+=revenue;}));
  const topP=Object.values(pmap).sort((a,b)=>b.units-a.units||b.revenue-a.revenue).slice(0,10),topV=Object.values(vmap).sort((a,b)=>b.units-a.units||b.revenue-a.revenue).slice(0,10);
  $('topProductsTable').innerHTML=topP.map((x,i)=>`<tr><td><strong>${i+1}. ${esc(x.name)}</strong></td><td>${x.units}</td><td>${money(x.revenue)}</td></tr>`).join('')||'<tr><td colspan="3" class="empty-cell">No sales data yet.</td></tr>';
  $('topVariantsTable').innerHTML=topV.map((x,i)=>`<tr><td><strong>${i+1}. ${esc(x.name)}</strong></td><td>${esc(x.product)}</td><td>${x.units}</td><td>${money(x.revenue)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty-cell">No variant sales yet.</td></tr>';
}
function renderEmailLog(){const arr=emailLog();$('emailLogTable').innerHTML=arr.map(x=>`<tr><td>${new Date(x.date).toLocaleString()}</td><td>${esc(x.type||'Email')}</td><td>${esc(x.to||'—')}</td><td>${esc(x.subject||'—')}</td><td>${esc(x.status||'Queued')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty-cell">No email events yet.</td></tr>'}
function openShipmentDialog(index){const os=orders(),o=os[index];if(!o)return;const d=$('shipmentDialog');$('shipmentOrderIndex').value=index;$('shipmentOrderId').textContent=o.id;$('shipmentCarrier').value=o.trackingCarrier||'SF Express';$('shipmentTrackingNumber').value=o.trackingNumber||'';$('shipmentTrackingUrl').value=o.trackingUrl||'';$('shipmentEmailCustomer').checked=true;d.showModal()}
function closeShipmentDialog(){const d=$('shipmentDialog');if(d?.open)d.close()}
async function saveShipment(){const i=Number($('shipmentOrderIndex').value),os=orders(),o=os[i];if(!o)return;const carrier=$('shipmentCarrier').value,trackingNumber=$('shipmentTrackingNumber').value.trim(),trackingUrl=$('shipmentTrackingUrl').value.trim(),emailCustomer=$('shipmentEmailCustomer').checked;if(!trackingNumber){$('shipmentTrackingNumber').focus();return}o.fulfilment='Shipped';o.trackingCarrier=carrier;o.trackingNumber=trackingNumber;o.trackingUrl=trackingUrl;o.shippedAt=new Date().toISOString();localStorage.setItem(ZB_ORDERS,JSON.stringify(os));if(emailCustomer&&o.email){logEmailEvent({type:'Shipping confirmation',to:o.email,subject:`Your ZIONBURG order has shipped — ${o.id}`,orderId:o.id});fetch('/.netlify/functions/send-shipping-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order:o})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(()=>{const arr=emailLog();let changed=false;arr.forEach(x=>{if(x.orderId===o.id&&x.type==='Shipping confirmation'&&x.status==='Queued (prototype)'){x.status='Sent via Netlify';changed=true}});if(changed)localStorage.setItem(ZB_EMAIL_LOG,JSON.stringify(arr));renderEmailLog()}).catch(()=>{renderEmailLog()})}closeShipmentDialog();renderSales();renderAnalytics();renderEmailLog();showSaveToast()}
function renderSubs(){const ss=subs();$('subActive').textContent=ss.filter(s=>s.status==='Active').length;$('subCustomers').textContent=new Set(ss.map(s=>s.email)).size;$('subValue').textContent=money(ss.filter(s=>s.status==='Active').reduce((a,s)=>a+Number(s.amount||0),0));$('subscriptionTable').innerHTML=ss.map(s=>`<tr><td><span class="status-pill success">${esc(s.status)}</span></td><td>${esc(s.email)}</td><td>${esc(s.item)}</td><td>${esc(s.cadence)}</td><td>${money(s.amount)}</td><td>${new Date(s.nextBilling).toLocaleDateString()}</td></tr>`).join('')||'<tr><td colspan="6" class="empty-cell">No subscriptions yet.</td></tr>'}

function boolOptions(v){return `<option value="true" ${v!==false?'selected':''}>Yes</option><option value="false" ${v===false?'selected':''}>No</option>`}
function statusBadge(v){return `<span class="status-pill ${v==='active'?'success':v==='draft'?'neutral':'muted'}">${esc(v||'draft')}</span>`}

function stockistTypeOptions(v){const types=['Physical Store','Online Store','TikTok Shop','Shopee','Marketplace','Distributor','Partner','Pop-up / Event','Other'];const extra=v&&!types.includes(v)?`<option value="${esc(v)}" selected>${esc(v)}</option>`:'';return extra+types.map(x=>`<option value="${x}" ${v===x?'selected':''}>${x}</option>`).join('')}
function countryOptions(v){const countries=['Hong Kong','China','Macau','Singapore','Japan','South Korea','Taiwan','Thailand','Malaysia','Philippines','United Kingdom','United States','Australia','Other'];const extra=v&&!countries.includes(v)?`<option value="${esc(v)}" selected>${esc(v)}</option>`:'';return extra+countries.map(x=>`<option value="${x}" ${v===x?'selected':''}>${x}</option>`).join('')}
function genericEditor(type,obj,i){
  if(type==='page')return `<div class="stack-editor" data-page="${i}"><label>Title<input data-k="title" value="${esc(obj.title)}"></label><label>Slug<input data-k="slug" value="${esc(obj.slug)}"></label><label class="grow">Content<input data-k="body" value="${esc(obj.body)}"></label>${miniTranslations(obj,[{key:'title',label:'Title'},{key:'body',label:'Content'}])}<button class="text-button danger-text" data-remove="page">Remove</button></div>`;
  if(type==='nav')return `<div class="stack-editor" data-nav="${i}"><label>Label<input data-k="label" value="${esc(obj.label)}"></label><label>Type<select data-k="type"><option value="link" ${obj.type==='link'?'selected':''}>Link</option><option value="products" ${obj.type==='products'?'selected':''}>Products dropdown</option></select></label><label class="grow">Destination<input data-k="href" value="${esc(obj.href||'')}"></label><label>Visible<select data-k="visible">${boolOptions(obj.visible)}</select></label>${miniTranslations(obj,[{key:'label',label:'Label'}])}<button class="text-button danger-text" data-remove="nav">Remove</button></div>`;
  if(type==='discount')return `<div class="stack-editor" data-discount="${i}"><label>Code<input data-k="code" value="${esc(obj.code)}"></label><label>Type<select data-k="type"><option value="percent" ${obj.type==='percent'?'selected':''}>Percent</option><option value="flat" ${obj.type==='flat'?'selected':''}>Flat HK$</option></select></label><label>Value<input data-k="value" type="number" value="${obj.value}"></label><label>Enabled<select data-k="enabled">${boolOptions(obj.enabled)}</select></label><button class="text-button danger-text" data-remove="discount">Remove</button></div>`;
  if(type==='subplan')return `<div class="stack-editor" data-subplan="${i}"><label>Label<input data-k="label" value="${esc(obj.label)}"></label><label>Value<input data-k="value" value="${esc(obj.value)}"></label><span class="grow"></span><button class="text-button danger-text" data-remove="subplan">Remove</button></div>`;
  if(type==='stockist')return `<div class="stockist-editor" data-stockist="${i}"><div class="stockist-editor-head"><strong>${esc(obj.name||'Stockist')}</strong><label class="mini-switch"><input type="checkbox" data-k="active" ${obj.active!==false?'checked':''}><span>Active</span></label></div><div class="stockist-editor-grid"><label>Name<input data-k="name" value="${esc(obj.name||'')}"></label><label>Type<select data-k="type">${stockistTypeOptions(obj.type||'Physical Store')}</select></label><label>Country / market<select data-k="country">${countryOptions(obj.country||'Hong Kong')}</select></label><label>Region / state<input data-k="region" value="${esc(obj.region||'')}"></label><label>City<input data-k="city" value="${esc(obj.city||'')}"></label><label class="wide">Address / location<input data-k="address" value="${esc(obj.address||'')}"></label><label class="wide">Store URL<input data-k="url" value="${esc(obj.url||'')}" placeholder="https://..."></label></div><button class="text-button danger-text" data-remove="stockist">Remove stockist</button></div>`;
  if(type==='partner'||type==='friend')return `<div class="community-editor" data-${type}="${i}"><div class="community-editor-preview">${obj.image?`<img src="${esc(obj.image)}" alt="">`:'<span>No image</span>'}</div><div class="community-editor-fields"><div class="three-col"><label>Name<input data-k="name" value="${esc(obj.name||'')}"></label><label>Type<input data-k="type" value="${esc(obj.type||'')}"></label><label>Image fit<select data-k="imageFit"><option value="cover" ${obj.imageFit!=='contain'?'selected':''}>Photo / cover</option><option value="contain" ${obj.imageFit==='contain'?'selected':''}>Logo / contain</option></select></label></div><label>Note<textarea data-k="note" rows="2">${esc(obj.note||'')}</textarea></label><label>Image / logo URL<input data-k="image" value="${esc(obj.image||'')}" placeholder="https://..."></label><label>Upload image<input type="file" accept="image/*" data-community-upload="${type}" data-community-index="${i}"></label><label>Website / social URL<input data-k="url" value="${esc(obj.url||'')}" placeholder="https://..."></label>${miniTranslations(obj,[{key:'name',label:'Name'},{key:'note',label:'Note'}])}<button class="text-button danger-text" data-remove="${type}">Remove</button></div></div>`;
  const noteKey='note';return `<div class="stack-editor" data-${type}="${i}"><label>Name<input data-k="name" value="${esc(obj.name)}"></label><label>Type<input data-k="type" value="${esc(obj.type||'')}"></label><label class="grow">Note<input data-k="${noteKey}" value="${esc(obj[noteKey]||'')}"></label><button class="text-button danger-text" data-remove="${type}">Remove</button></div>`
}
function renderFooterLinkEditors(){const f=adminState.footer||defaults.footer;$('footerLinkEditors').innerHTML=(f.links||[]).map((x,i)=>`<div class="stack-editor" data-footer-link="${i}"><label>Label<input data-k="label" value="${esc(x.label||'')}"></label><label class="grow">Destination<input data-k="href" value="${esc(x.href||'')}"></label><label>Visible<select data-k="visible">${boolOptions(x.visible)}</select></label>${miniTranslations(x,[{key:'label',label:'Label'}])}<button class="text-button danger-text" data-remove-footer-link="${i}">Remove</button></div>`).join('')||'<p class="empty-copy">No footer links. The footer will stay minimal.</p>'}
function captureFooterLinks(){const f=adminState.footer||(adminState.footer=clone(defaults.footer));f.links=f.links||[];document.querySelectorAll('[data-footer-link]').forEach(el=>{const i=+el.dataset.footerLink;if(!f.links[i])return;el.querySelectorAll('[data-k]').forEach(inp=>{let v=inp.value;if(inp.dataset.k==='visible')v=v==='true';f.links[i][inp.dataset.k]=v});el.querySelectorAll('[data-trans-locale]').forEach(inp=>{f.links[i].translations=f.links[i].translations||{};const loc=inp.dataset.transLocale;f.links[i].translations[loc]=f.links[i].translations[loc]||{};f.links[i].translations[loc][inp.dataset.transField]=inp.value})})}
function renderGenericEditors(){
  $('pageEditors').innerHTML=(adminState.pages||[]).map((x,i)=>genericEditor('page',x,i)).join('');
  $('navEditors').innerHTML=(adminState.nav||[]).map((x,i)=>genericEditor('nav',x,i)).join('');
  $('stockistEditors').innerHTML=(adminState.stockists||[]).map((x,i)=>genericEditor('stockist',x,i)).join('');
  $('partnerEditors').innerHTML=(adminState.partners||[]).map((x,i)=>genericEditor('partner',x,i)).join('');
  $('friendEditors').innerHTML=(adminState.friends||[]).map((x,i)=>genericEditor('friend',x,i)).join('');
  $('discountEditors').innerHTML=(adminState.discounts||[]).map((x,i)=>genericEditor('discount',x,i)).join('');
  $('subscriptionPlanEditors').innerHTML=(adminState.subscriptions?.plans||[]).map((x,i)=>genericEditor('subplan',x,i)).join('');renderFooterLinkEditors();
}
function captureGenericEditors(){
  const map={page:'pages',nav:'nav',stockist:'stockists',partner:'partners',friend:'friends',discount:'discounts'};
  for(const type of Object.keys(map))document.querySelectorAll(`[data-${type}]`).forEach(el=>{const target=adminState[map[type]],i=+el.dataset[type];if(!target?.[i])return;el.querySelectorAll('[data-k]').forEach(inp=>{let v=inp.value;if(inp.type==='number')v=v===''?null:Number(v);if(inp.type==='checkbox')v=inp.checked;else if(['visible','enabled','active'].includes(inp.dataset.k))v=v==='true';target[i][inp.dataset.k]=v});el.querySelectorAll('[data-trans-locale]').forEach(inp=>{target[i].translations=target[i].translations||{};const loc=inp.dataset.transLocale;target[i].translations[loc]=target[i].translations[loc]||{};target[i].translations[loc][inp.dataset.transField]=inp.value})});
  document.querySelectorAll('[data-subplan]').forEach(el=>{const i=+el.dataset.subplan;if(!adminState.subscriptions.plans[i])return;el.querySelectorAll('[data-k]').forEach(inp=>adminState.subscriptions.plans[i][inp.dataset.k]=inp.value)});
}

const HOME_MEDIA_LABELS=['Hero','Refreshing Body Wipes','Lifestyle — Movement','Lifestyle — Travel','Lifestyle — Everyday','Lifestyle — Cleaner Tomorrow','Brand commitment'];
function homeMediaFlat(){const h=adminState.homepageMedia||defaults.homepageMedia;return [h.hero,h.signature,...(h.lifestyle||[]),h.commitment]}
function setHomeMediaFlat(items){adminState.homepageMedia={hero:items[0],signature:items[1],lifestyle:items.slice(2,6),commitment:items[6]}}
function mediaPreview(m){if(!m?.src)return '<div class="media-preview-empty">No media</div>';if(m.type==='youtube')return `<div class="media-preview-video">YOUTUBE</div>`;if(m.type==='video')return m.poster?`<img src="${esc(m.poster)}" alt="">`:'<div class="media-preview-video">VIDEO</div>';return `<img src="${esc(m.src)}" alt="">`}
function mediaEditor(m,i,scope,label,removable=false){m=m||{};return `<div class="media-editor" data-media-scope="${scope}" data-media-index="${i}"><div class="media-editor-head"><strong>${esc(label)}</strong>${removable?`<div class="media-order-actions"><button class="icon-square" type="button" data-move-product-media="up" data-media-order-index="${i}">↑</button><button class="icon-square" type="button" data-move-product-media="down" data-media-order-index="${i}">↓</button><button class="text-button danger-text" type="button" data-remove-product-media="${i}">Remove</button></div>`:''}</div><div class="asset-preview media-asset-preview">${mediaPreview(m)}</div><div class="two-col"><label>Media type<select data-media-k="type"><option value="image" ${m.type==='image'||!m.type?'selected':''}>Image</option><option value="video" ${m.type==='video'?'selected':''}>Video / MP4</option><option value="youtube" ${m.type==='youtube'?'selected':''}>YouTube</option></select></label><label>Alt / label<input data-media-k="alt" value="${esc(m.alt||'')}"></label></div><label>Media URL<input data-media-k="src" value="${esc(m.src||'')}" placeholder="Image, MP4/WebM or YouTube URL"></label><label>Upload image / small video<input class="media-upload" data-media-upload-scope="${scope}" data-media-upload-index="${i}" type="file" accept="image/*,video/mp4,video/webm"></label><label>Video poster image URL<input data-media-k="poster" value="${esc(m.poster||'')}" placeholder="Optional poster / fallback image"></label><div class="three-col"><label>Autoplay<select data-media-k="autoplay">${boolOptions(m.autoplay)}</select></label><label>Loop<select data-media-k="loop">${boolOptions(m.loop)}</select></label><label>Controls<select data-media-k="controls">${boolOptions(!!m.controls)}</select></label></div></div>`}
function renderHomeMediaEditors(){$('homepageMediaEditors').innerHTML=homeMediaFlat().map((m,i)=>mediaEditor(m,i,'home',HOME_MEDIA_LABELS[i],false)).join('')}
function captureHomeMedia(){const items=homeMediaFlat();document.querySelectorAll('[data-media-scope="home"]').forEach(el=>{const i=+el.dataset.mediaIndex;if(!items[i])return;el.querySelectorAll('[data-media-k]').forEach(inp=>{let v=inp.value;if(['autoplay','loop','controls'].includes(inp.dataset.mediaK))v=v==='true';items[i][inp.dataset.mediaK]=v})});setHomeMediaFlat(items)}

function renderBenefitEditors(){$('benefitEditors').innerHTML=(adminState.benefits||[]).map((b,i)=>`<div class="asset-editor" data-benefit="${i}"><div class="asset-preview"><img src="${esc(b.icon)}" alt=""></div><label>Title<input data-k="title" value="${esc(b.title)}"></label><label>Subtext<input data-k="subtitle" value="${esc(b.subtitle)}"></label>${miniTranslations(b,[{key:'title',label:'Title'},{key:'subtitle',label:'Subtext'}])}<label>Icon URL / data URI<input data-k="icon" value="${esc(b.icon)}"></label><label>Upload SVG / image<input class="benefit-upload" data-benefit-upload="${i}" type="file" accept="image/svg+xml,image/png,image/jpeg,image/webp"></label></div>`).join('')}
function captureBenefits(){document.querySelectorAll('[data-benefit]').forEach(el=>{const i=+el.dataset.benefit;if(!adminState.benefits[i])return;el.querySelectorAll('[data-k]').forEach(inp=>adminState.benefits[i][inp.dataset.k]=inp.value);el.querySelectorAll('[data-trans-locale]').forEach(inp=>{const b=adminState.benefits[i];b.translations=b.translations||{};const loc=inp.dataset.transLocale;b.translations[loc]=b.translations[loc]||{};b.translations[loc][inp.dataset.transField]=inp.value})})}
function renderBrandingPreviews(){const b=adminState.branding||defaults.branding;$('navLogoPreview').innerHTML=b.logo?`<img src="${esc(b.logo)}" alt="logo preview">`:`<strong class="text-logo-preview">${esc(b.logoText||'ZIONBURG')}</strong>`;$('faviconPreview').innerHTML=b.favicon?`<img src="${esc(b.favicon)}" alt="favicon preview">`:''}


function enabledLanguages(){return (adminState.localization?.languages||defaults.localization.languages).filter(x=>x.enabled!==false)}
function translationLanguages(){const def=adminState.localization?.defaultLocale||'en';return enabledLanguages().filter(x=>x.code!==def)}
function translationFieldsHTML(obj,scope){const langs=translationLanguages();if(!langs.length)return '<p class="empty-copy">Enable another language under Markets & languages to add translations.</p>';obj.translations=obj.translations||{};return `<div class="translation-card-head"><strong>Translations</strong><small>Blank fields fall back to the source language.</small></div>`+langs.map(l=>{const t=obj.translations[l.code]||{};return `<div class="translation-block" data-translation-scope="${scope}" data-locale="${esc(l.code)}"><div class="translation-locale">${esc(l.label)}</div><label>Title<input data-tk="title" value="${esc(t.title||'')}"></label><label>Description<textarea data-tk="description" rows="3">${esc(t.description||'')}</textarea></label></div>`}).join('')}
function captureTranslationFields(obj,scope){if(!obj)return;obj.translations=obj.translations||{};document.querySelectorAll(`[data-translation-scope="${scope}"]`).forEach(el=>{const locale=el.dataset.locale;obj.translations[locale]=obj.translations[locale]||{};el.querySelectorAll('[data-tk]').forEach(inp=>obj.translations[locale][inp.dataset.tk]=inp.value)})}
function miniTranslations(obj,fields){const langs=translationLanguages();if(!langs.length)return '';obj.translations=obj.translations||{};return `<div class="stack-translations">${langs.map(l=>fields.map(f=>`<label>${esc(l.label)} — ${esc(f.label)}<input data-trans-locale="${esc(l.code)}" data-trans-field="${esc(f.key)}" value="${esc(obj.translations?.[l.code]?.[f.key]||'')}"></label>`).join('')).join('')}</div>`}

function interfaceTranslationLanguages(){const def=adminState.localization?.defaultLocale||'en';return enabledLanguages().filter(x=>x.code!==def)}
function renderInterfaceTranslationEditor(){
  const host=$('interfaceTranslationEditors'),sel=$('interfaceTranslationLocale');if(!host||!sel)return;
  const langs=interfaceTranslationLanguages();if(!langs.length){sel.innerHTML='';host.innerHTML='<p class="empty-copy">Enable another language to translate the storefront interface.</p>';selectedInterfaceLocale=null;return}
  if(!selectedInterfaceLocale||!langs.some(x=>x.code===selectedInterfaceLocale))selectedInterfaceLocale=langs[0].code;
  sel.innerHTML=langs.map(l=>`<option value="${esc(l.code)}" ${l.code===selectedInterfaceLocale?'selected':''}>${esc(l.label)}</option>`).join('');
  adminState.localization.interfaceTranslations=adminState.localization.interfaceTranslations||{};
  const custom=adminState.localization.interfaceTranslations[selectedInterfaceLocale]||(adminState.localization.interfaceTranslations[selectedInterfaceLocale]={});
  const built=defaultUiTranslations[selectedInterfaceLocale]||{};
  const groups={};uiPhraseCatalog.forEach(item=>(groups[item.group]||(groups[item.group]=[])).push(item));
  host.innerHTML=Object.entries(groups).map(([group,items])=>`<section class="ui-translation-group"><div class="ui-translation-group-head"><h3>${esc(group)}</h3><span>${items.length} phrases</span></div><div class="ui-translation-list">${items.map(item=>`<label class="ui-translation-row"><span class="ui-translation-source"><small>English</small><strong>${esc(item.en)}</strong></span><span class="ui-translation-target"><small>${esc((langs.find(x=>x.code===selectedInterfaceLocale)||{}).label||selectedInterfaceLocale)}</small><input data-ui-translation-key="${esc(item.key)}" value="${esc(custom[item.key]!==undefined?custom[item.key]:(built[item.key]||''))}" placeholder="${esc(built[item.key]||'')}"></span></label>`).join('')}</div></section>`).join('');
  const editLink=$('openTranslationEditMode');if(editLink){const p=(adminState.catalogProducts||[]).find(x=>x.status==='active')||adminState.catalogProducts?.[0];editLink.href=`product.html?product=${encodeURIComponent(p?.handle||'')}&edit=translate&locale=${encodeURIComponent(selectedInterfaceLocale)}`;}
}
function captureInterfaceTranslations(locale=selectedInterfaceLocale){
  if(!locale||!$('interfaceTranslationEditors'))return;
  adminState.localization=adminState.localization||clone(defaults.localization);adminState.localization.interfaceTranslations=adminState.localization.interfaceTranslations||{};
  const ob=adminState.localization.interfaceTranslations[locale]||(adminState.localization.interfaceTranslations[locale]={});
  document.querySelectorAll('[data-ui-translation-key]').forEach(inp=>ob[inp.dataset.uiTranslationKey]=inp.value);
}
function renderLanguageSettings(){
  adminState.localization=adminState.localization||clone(defaults.localization);const langs=adminState.localization.languages||clone(defaults.localization.languages);
  $('defaultLocale').innerHTML=langs.filter(x=>x.enabled!==false).map(x=>`<option value="${esc(x.code)}" ${x.code===adminState.localization.defaultLocale?'selected':''}>${esc(x.label)}</option>`).join('');
  $('languageChecks').innerHTML=langs.map((x,i)=>`<label class="check-row"><input type="checkbox" data-language-index="${i}" ${x.enabled!==false?'checked':''} ${x.code==='en'?'disabled':''}><span><strong>${esc(x.label)}</strong><small>${esc(x.code)}</small></span></label>`).join('');
  const nonDefault=langs.filter(x=>x.enabled!==false&&x.code!==adminState.localization.defaultLocale),cts=adminState.localization.contentTranslations||(adminState.localization.contentTranslations={});
  $('globalTranslationEditors').innerHTML=nonDefault.map(l=>{const t=cts[l.code]||{};return `<div class="translation-block" data-global-translation="${esc(l.code)}"><div class="translation-locale">${esc(l.label)}</div><label>Hero eyebrow<input data-gtk="heroEyebrow" value="${esc(t.heroEyebrow||'')}"></label><label>Hero title<textarea data-gtk="heroTitle" rows="3">${esc(t.heroTitle||'')}</textarea></label><label>Hero subtitle<input data-gtk="heroSubtitle" value="${esc(t.heroSubtitle||'')}"></label><label>Footer tagline<input data-gtk="footerTagline" value="${esc(t.footerTagline||'')}"></label></div>`}).join('')||'<p class="empty-copy">Enable another language to edit translated global copy.</p>';
  renderInterfaceTranslationEditor();
}
function captureLanguageSettings(){
  captureInterfaceTranslations();
  adminState.localization=adminState.localization||clone(defaults.localization);const langs=adminState.localization.languages||clone(defaults.localization.languages);document.querySelectorAll('[data-language-index]').forEach(inp=>{const i=+inp.dataset.languageIndex;if(langs[i])langs[i].enabled=inp.checked||langs[i].code==='en'});adminState.localization.languages=langs;const enabled=langs.filter(x=>x.enabled!==false);adminState.localization.defaultLocale=enabled.some(x=>x.code===$('defaultLocale').value)?$('defaultLocale').value:(enabled[0]?.code||'en');adminState.localization.contentTranslations=adminState.localization.contentTranslations||{};document.querySelectorAll('[data-global-translation]').forEach(el=>{const locale=el.dataset.globalTranslation,ob=adminState.localization.contentTranslations[locale]||(adminState.localization.contentTranslations[locale]={});el.querySelectorAll('[data-gtk]').forEach(inp=>ob[inp.dataset.gtk]=inp.value)});
}
function marketCurrencyOptions(v){return ['HKD','USD','SGD','GBP','EUR','AUD','JPY','CNY','CAD'].map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}
function renderMarketEditors(){
  adminState.markets=adminState.markets||clone(defaults.markets);$('taxEngine').value=adminState.markets.taxEngine||'manual';$('taxOnShipping').checked=!!adminState.markets.taxOnShipping;
  $('marketEditors').innerHTML=(adminState.markets.items||[]).map((m,i)=>`<div class="market-card" data-market-index="${i}"><div class="market-card-head"><div><strong>${esc(m.name||'Market')}</strong><small>${esc((m.countries||[]).join(', ')||'No countries')}</small></div><label class="mini-switch"><input type="checkbox" data-mk="enabled" ${m.enabled!==false?'checked':''}><span>Active</span></label></div><div class="market-grid"><label>Market name<input data-mk="name" value="${esc(m.name||'')}"></label><label>Countries / regions<input data-mk="countries" value="${esc((m.countries||[]).join(', '))}" placeholder="Hong Kong, Singapore"></label><label>Currency<select data-mk="currency">${marketCurrencyOptions(m.currency||'HKD')}</select></label><label>Currency symbol<input data-mk="symbol" value="${esc(m.symbol||'')}"></label><label>FX rate from HKD<input data-mk="fxRate" type="number" min="0" step="0.0001" value="${Number(m.fxRate||1)}"></label><label>Tax rate (%)<input data-mk="taxRate" type="number" min="0" step="0.01" value="${Number(m.taxRate||0)}"></label><label>Shipping fee (HK$ base)<input data-mk="shippingFee" type="number" min="0" step="1" value="${Number(m.shippingFee||0)}"></label><label>Free shipping threshold (HK$ base)<input data-mk="freeShippingThreshold" type="number" min="0" step="1" value="${Number(m.freeShippingThreshold||0)}"></label><label>Delivery estimate<input data-mk="deliveryEstimate" value="${esc(m.deliveryEstimate||'')}"></label></div>${m.id==='hk'?'<small class="admin-field-note">Hong Kong is the base market and cannot be deleted.</small>':`<button class="text-button danger-text" data-remove-market="${i}">Remove market</button>`}</div>`).join('');
}
function captureMarketEditors(){
  adminState.markets=adminState.markets||clone(defaults.markets);adminState.markets.taxEngine=$('taxEngine').value;adminState.markets.taxOnShipping=$('taxOnShipping').checked;document.querySelectorAll('[data-market-index]').forEach(el=>{const i=+el.dataset.marketIndex,m=adminState.markets.items[i];if(!m)return;el.querySelectorAll('[data-mk]').forEach(inp=>{const k=inp.dataset.mk;let v=inp.type==='checkbox'?inp.checked:inp.value;if(['fxRate','taxRate','shippingFee','freeShippingThreshold'].includes(k))v=Number(v||0);if(k==='countries')v=String(v).split(',').map(x=>x.trim()).filter(Boolean);m[k]=v})});if(!adminState.markets.items.some(x=>x.id===adminState.markets.defaultMarketId&&x.enabled!==false))adminState.markets.defaultMarketId=adminState.markets.items.find(x=>x.enabled!==false)?.id||'hk';
}

function productThumb(p){const m=(p.media||[]).find(x=>x?.src&&x.type==='image');const v=(p.variants||[]).find(x=>x?.image);return m?.src||v?.image||''}
function productInventory(p){return (p.variants||[]).reduce((s,v)=>s+Number(v.inventory||0),0)}
function renderProductList(){
  $('productListView').hidden=false;$('productEditorView').hidden=true;selectedProductId=null;
  const term=($('productSearch')?.value||'').toLowerCase(),filter=$('productStatusFilter')?.value||'all';let list=(adminState.catalogProducts||[]).filter(p=>(filter==='all'||p.status===filter)&&(!term||[p.title,p.vendor,p.productType].join(' ').toLowerCase().includes(term)));
  $('productTableBody').innerHTML=list.map(p=>`<tr class="clickable-row" data-edit-product="${p.id}"><td><div class="product-cell">${productThumb(p)?`<img src="${esc(productThumb(p))}" alt="">`:'<div class="product-thumb-empty"></div>'}<div><strong>${esc(p.title)}</strong><small>${esc(p.vendor||'ZIONBURG')}</small></div></div></td><td>${statusBadge(p.status)}</td><td>${productInventory(p)} in stock</td><td>${esc(p.productType||'—')}</td><td>${(p.variants||[]).length}</td><td><button class="text-button" data-edit-product="${p.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty-cell">No products found.</td></tr>';
}
function currentProduct(){return (adminState.catalogProducts||[]).find(p=>p.id===selectedProductId)}
function openProductEditor(id){selectedProductId=id;$('productListView').hidden=true;$('productEditorView').hidden=false;renderProductEditor();window.scrollTo({top:0,behavior:'smooth'})}
function renderProductEditor(){
  const p=currentProduct();if(!p)return renderProductList();
  $('productTitle').value=p.title||'';$('productDescription').value=p.description||'';$('productHandle').value=p.handle||'';$('productVendor').value=p.vendor||'';$('productType').value=p.productType||'';$('productStatus').value=p.status||'draft';$('archiveProduct').textContent=p.status==='archived'?'Unarchive':'Archive';$('productShowInNav').checked=p.showInNav!==false;$('productSubscriptionEligible').checked=p.subscriptionEligible!==false;
  $('productCollectionChecks').innerHTML=(adminState.collections||[]).map(c=>`<label class="check-row"><input type="checkbox" value="${c.id}" ${((p.collectionIds||[]).includes(c.id))?'checked':''}><span>${esc(c.title)}</span></label>`).join('')||'<p class="empty-copy">No collections yet.</p>';
  $('productTranslationEditors').innerHTML=translationFieldsHTML(p,'product');const translateLink=$('translateProductOnStorefront');if(translateLink){const locale=interfaceTranslationLanguages()[0]?.code||'zh-HK';translateLink.href=`product.html?product=${encodeURIComponent(p.handle||p.id)}&edit=translate&locale=${encodeURIComponent(locale)}`;}renderVariantEditors();renderProductMediaEditors();
}
function variantEditor(v,i){return `<div class="variant-card" data-variant-index="${i}"><div class="variant-card-head"><div><span class="variant-swatch" style="background:${v.color||'#ddd'}"></span><strong>${esc(v.name||'Variant')}</strong></div><button class="text-button danger-text" data-remove-variant="${i}">Remove</button></div><div class="variant-grid"><label>Name<input data-vk="name" value="${esc(v.name||'')}"></label><label>State / descriptor<input data-vk="state" value="${esc(v.state||'')}"></label><label>Price (HK$)<input data-vk="price" type="number" min="0" value="${Number(v.price||0)}"></label><label>SKU<input data-vk="sku" value="${esc(v.sku||'')}"></label><label>Inventory<input data-vk="inventory" type="number" min="0" value="${Number(v.inventory||0)}"></label><label>Colour<input data-vk="color" type="color" value="${v.color||'#dddddd'}"></label><label class="variant-wide">Image URL<input data-vk="image" value="${esc(v.image||'')}"></label><label>Active<select data-vk="active">${boolOptions(v.active)}</select></label></div>${miniTranslations(v,[{key:'name',label:'Name'},{key:'state',label:'State / descriptor'}])}</div>`}
function renderVariantEditors(){const p=currentProduct();$('variantEditors').innerHTML=(p?.variants||[]).map(variantEditor).join('')||'<p class="empty-copy">No variants yet.</p>'}
function captureVariants(){const p=currentProduct();if(!p)return;document.querySelectorAll('[data-variant-index]').forEach(el=>{const i=+el.dataset.variantIndex;if(!p.variants[i])return;el.querySelectorAll('[data-vk]').forEach(inp=>{let v=inp.value;if(['price','inventory'].includes(inp.dataset.vk))v=Number(v||0);if(inp.dataset.vk==='active')v=v==='true';p.variants[i][inp.dataset.vk]=v});el.querySelectorAll('[data-trans-locale]').forEach(inp=>{const v=p.variants[i];v.translations=v.translations||{};const loc=inp.dataset.transLocale;v.translations[loc]=v.translations[loc]||{};v.translations[loc][inp.dataset.transField]=inp.value})})}
function renderProductMediaEditors(){const p=currentProduct();$('productMediaEditors').innerHTML=(p?.media||[]).map((m,i)=>mediaEditor(m,i,'product',`Media ${i+1}`,true)).join('')||'<p class="empty-copy">No media yet. Add your first image or video.</p>'}
function captureProductMedia(){const p=currentProduct();if(!p)return;document.querySelectorAll('[data-media-scope="product"]').forEach(el=>{const i=+el.dataset.mediaIndex;if(!p.media[i])return;el.querySelectorAll('[data-media-k]').forEach(inp=>{let v=inp.value;if(['autoplay','loop','controls'].includes(inp.dataset.mediaK))v=v==='true';p.media[i][inp.dataset.mediaK]=v})})}
function captureProductEditor(){
  const p=currentProduct();if(!p||$('productEditorView')?.hidden)return;captureVariants();captureProductMedia();captureTranslationFields(p,'product');p.title=$('productTitle').value.trim()||'Untitled product';p.description=$('productDescription').value;p.handle=slugify($('productHandle').value||p.title);p.vendor=$('productVendor').value;p.productType=$('productType').value;p.status=$('productStatus').value;p.showInNav=$('productShowInNav').checked;p.subscriptionEligible=$('productSubscriptionEligible').checked;p.collectionIds=[...$('productCollectionChecks').querySelectorAll('input:checked')].map(x=>x.value);(adminState.collections||[]).forEach(c=>{c.productIds=c.productIds||[];c.productIds=c.productIds.filter(id=>id!==p.id);if(p.collectionIds.includes(c.id))c.productIds.push(p.id)})
}
function addNewProduct(){captureAll();const p={id:uid('prod'),title:'Untitled product',handle:`untitled-product-${Date.now().toString().slice(-4)}`,status:'draft',vendor:'ZIONBURG',productType:'',description:'',showInNav:false,subscriptionEligible:true,collectionIds:[],variants:[{id:uid('var'),name:'Default',state:'',price:0,sku:'',color:'#d8d8d8',image:'',inventory:0,active:true}],media:[]};adminState.catalogProducts.push(p);openProductEditor(p.id)}

function renderCollectionList(){$('collectionListView').hidden=false;$('collectionEditorView').hidden=true;selectedCollectionId=null;$('collectionTableBody').innerHTML=(adminState.collections||[]).map(c=>`<tr class="clickable-row" data-edit-collection="${c.id}"><td><strong>${esc(c.title)}</strong><small class="table-sub">/${esc(c.handle)}</small></td><td>${statusBadge(c.status)}</td><td>${(c.productIds||[]).length}</td><td><button class="text-button" data-edit-collection="${c.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty-cell">No collections yet.</td></tr>'}
function currentCollection(){return (adminState.collections||[]).find(c=>c.id===selectedCollectionId)}
function openCollectionEditor(id){selectedCollectionId=id;$('collectionListView').hidden=true;$('collectionEditorView').hidden=false;renderCollectionEditor();window.scrollTo({top:0,behavior:'smooth'})}
function renderCollectionEditor(){const c=currentCollection();if(!c)return renderCollectionList();$('collectionTitle').value=c.title||'';$('collectionDescription').value=c.description||'';$('collectionTranslationEditors').innerHTML=translationFieldsHTML(c,'collection');$('collectionHandle').value=c.handle||'';$('collectionStatus').value=c.status||'active';$('collectionProductChecks').innerHTML=(adminState.catalogProducts||[]).map(p=>`<label class="check-row product-check"><input type="checkbox" value="${p.id}" ${((c.productIds||[]).includes(p.id))?'checked':''}><span>${productThumb(p)?`<img src="${esc(productThumb(p))}" alt="">`:''}<b>${esc(p.title)}</b><small>${esc(p.productType||'Product')}</small></span></label>`).join('')||'<p class="empty-copy">No products yet.</p>'}
function captureCollectionEditor(){const c=currentCollection();if(!c||$('collectionEditorView')?.hidden)return;captureTranslationFields(c,'collection');c.title=$('collectionTitle').value.trim()||'Untitled collection';c.description=$('collectionDescription').value;c.handle=slugify($('collectionHandle').value||c.title);c.status=$('collectionStatus').value;c.productIds=[...$('collectionProductChecks').querySelectorAll('input:checked')].map(x=>x.value);(adminState.catalogProducts||[]).forEach(p=>{p.collectionIds=p.collectionIds||[];p.collectionIds=p.collectionIds.filter(id=>id!==c.id);if(c.productIds.includes(p.id))p.collectionIds.push(c.id)})}
function addNewCollection(){captureAll();const c={id:uid('col'),title:'Untitled collection',handle:`collection-${Date.now().toString().slice(-4)}`,status:'draft',description:'',productIds:[]};adminState.collections.push(c);openCollectionEditor(c.id)}

function bundleScopeTargetOptions(b){if(b.scopeType==='all')return '<option value="">Entire store</option>';const list=b.scopeType==='collection'?adminState.collections:adminState.catalogProducts;return (list||[]).map(x=>`<option value="${x.id}" ${b.scopeId===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}
function renderBundleEditors(){$('bundleEditors').innerHTML=(adminState.bundles||[]).map((b,i)=>`<div class="bundle-card" data-bundle="${i}"><div class="bundle-card-head"><div><strong>${esc(b.name||'Bundle')}</strong><small>${b.scopeType==='all'?'All products':b.scopeType==='collection'?'Collection':'Product'}</small></div><label class="mini-switch"><input type="checkbox" data-bk="active" ${b.active!==false?'checked':''}><span>Active</span></label></div><div class="bundle-grid"><label>Name<input data-bk="name" value="${esc(b.name||'')}"></label><label>Quantity<input data-bk="qty" type="number" min="1" value="${Number(b.qty||1)}"></label><label>Flat price (HK$)<input data-bk="price" type="number" min="0" value="${b.price??''}" placeholder="Blank = variant price"></label><label>Badge<input data-bk="badge" value="${esc(b.badge||'')}"></label><label>Applies to<select data-bk="scopeType"><option value="product" ${b.scopeType==='product'?'selected':''}>Specific product</option><option value="collection" ${b.scopeType==='collection'?'selected':''}>Collection</option><option value="all" ${b.scopeType==='all'?'selected':''}>All products</option></select></label><label>Target<select data-bk="scopeId">${bundleScopeTargetOptions(b)}</select></label></div><button class="text-button danger-text" data-remove-bundle="${i}">Delete bundle</button></div>`).join('')||'<p class="empty-copy">No bundles yet.</p>'}
function captureBundles(){document.querySelectorAll('[data-bundle]').forEach(el=>{const i=+el.dataset.bundle,b=adminState.bundles[i];if(!b)return;el.querySelectorAll('[data-bk]').forEach(inp=>{let v=inp.type==='checkbox'?inp.checked:inp.value;if(['qty','price'].includes(inp.dataset.bk))v=v===''?null:Number(v);b[inp.dataset.bk]=v});if(b.scopeType==='all')b.scopeId=''})}

function renderSettings(){
  $('editEyebrow').value=adminState.homepage.eyebrow||'';$('editTitle').value=adminState.homepage.title||'';$('editSubtitle').value=adminState.homepage.subtitle||'';
  $('subscriptionStorefrontVisible').checked=adminState.subscriptions.storefrontVisible!==false;$('subscriptionLabel').value=adminState.subscriptions.label||'Subscribe & save';$('subscriptionDiscount').value=Number(adminState.subscriptions.discount||0);
  $('bundlesStorefrontVisible').checked=adminState.features?.bundlesStorefrontVisible===true;$('customerAccountsEnabled').checked=adminState.features?.customerAccounts!==false;
  $('salesEmails').value=adminState.settings.salesEmails||adminState.settings.internalEmail||'';$('adminEmails').value=adminState.settings.adminEmails||'';$('sendSalesOrder').checked=adminState.settings.sendSalesOrder!==false;$('sendSalesReceipt').checked=adminState.settings.sendSalesReceipt!==false;$('receiptFromName').value=adminState.settings.receiptFromName||'ZB';$('receiptPrefix').value=adminState.settings.receiptPrefix||'ZB';const hkMarket=(adminState.markets?.items||[]).find(x=>x.id==='hk');$('shippingFee').value=hkMarket?.shippingFee??adminState.shipping.fee;$('freeShippingThreshold').value=hkMarket?.freeShippingThreshold??adminState.shipping.threshold;
  const f=adminState.footer||defaults.footer;$('footerTagline').value=f.tagline||'';$('socialInstagram').value=f.socials?.instagram||'';$('socialTiktok').value=f.socials?.tiktok||'';$('socialYoutube').value=f.socials?.youtube||'';$('socialFacebook').value=f.socials?.facebook||'';$('socialLinkedin').value=f.socials?.linkedin||'';
  const t=adminState.theme||defaults.theme;$('editFont').value=t.font||'Instrument Sans';$('editBodySize').value=String(t.bodySize||defaults.theme.bodySize||18);$('editBg').value=t.bg||defaults.theme.bg;$('editText').value=t.text||defaults.theme.text;$('editSurface').value=t.surface||defaults.theme.surface;$('editSoftSurface').value=t.softSurface||defaults.theme.softSurface;$('editSelectedFill').value=t.selectedFill||defaults.theme.selectedFill;$('editAccent').value=t.accent||defaults.theme.accent;$('editButton').value=t.button||defaults.theme.button;$('editButtonText').value=t.buttonText||defaults.theme.buttonText;$('editLine').value=t.line||defaults.theme.line;
  const b=adminState.branding||defaults.branding;$('navLogoUrl').value=b.logo||'';$('faviconUrl').value=b.favicon||'assets/favicon.svg';$('navLogoText').value=b.logoText||'ZIONBURG';$('mobileLogoText').value=b.mobileLogoText||'ZB';$('navLogoWidth').value=b.logoWidth||132;$('mobileLogoWidth').value=b.mobileLogoWidth||44;
  renderGenericEditors();renderHomeMediaEditors();renderBenefitEditors();renderBrandingPreviews();renderProductList();renderCollectionList();renderBundleEditors();renderLanguageSettings();renderMarketEditors();previewShipping();
}
function captureSettings(){
  adminState.homepage={eyebrow:$('editEyebrow').value,title:$('editTitle').value,subtitle:$('editSubtitle').value};adminState.subscriptions.enabled=true;adminState.subscriptions.storefrontVisible=$('subscriptionStorefrontVisible').checked;adminState.subscriptions.label=$('subscriptionLabel').value;adminState.subscriptions.discount=Number($('subscriptionDiscount').value||0);
  adminState.features={...(adminState.features||defaults.features),bundlesStorefrontVisible:$('bundlesStorefrontVisible').checked,customerAccounts:$('customerAccountsEnabled').checked};
  adminState.settings={...(adminState.settings||{}),internalEmail:$('salesEmails').value.split(/[;,\n]+/).map(x=>x.trim()).filter(Boolean)[0]||'',salesEmails:$('salesEmails').value,adminEmails:$('adminEmails').value,sendSalesOrder:$('sendSalesOrder').checked,sendSalesReceipt:$('sendSalesReceipt').checked,receiptFromName:$('receiptFromName').value,receiptPrefix:$('receiptPrefix').value};adminState.shipping={fee:Number($('shippingFee').value||0),threshold:Number($('freeShippingThreshold').value||0)};const hkMarket=(adminState.markets?.items||[]).find(x=>x.id==='hk');if(hkMarket){hkMarket.shippingFee=adminState.shipping.fee;hkMarket.freeShippingThreshold=adminState.shipping.threshold;}
  adminState.footer={...(adminState.footer||defaults.footer),tagline:$('footerTagline').value,socials:{instagram:$('socialInstagram').value.trim(),tiktok:$('socialTiktok').value.trim(),youtube:$('socialYoutube').value.trim(),facebook:$('socialFacebook').value.trim(),linkedin:$('socialLinkedin').value.trim()}};
  adminState.theme={font:$('editFont').value,bodySize:Number($('editBodySize').value||18),bg:$('editBg').value,text:$('editText').value,surface:$('editSurface').value,softSurface:$('editSoftSurface').value,selectedFill:$('editSelectedFill').value,accent:$('editAccent').value,button:$('editButton').value,buttonText:$('editButtonText').value,line:$('editLine').value};
  adminState.branding={...adminState.branding,logo:$('navLogoUrl').value.trim(),favicon:$('faviconUrl').value.trim()||'assets/favicon.svg',logoText:$('navLogoText').value.trim()||'ZIONBURG',mobileLogoText:$('mobileLogoText').value.trim()||'ZB',logoAlt:$('navLogoText').value.trim()||'ZIONBURG',logoWidth:Number($('navLogoWidth').value||132),mobileLogoWidth:Number($('mobileLogoWidth').value||44)};
}
function captureAll(){try{captureProductEditor();captureCollectionEditor();captureBundles();captureGenericEditors();captureFooterLinks();captureHomeMedia();captureBenefits();captureLanguageSettings();captureMarketEditors();captureSettings()}catch(e){console.warn('Admin capture skipped:',e)}}

function addGeneric(type,obj){captureAll();const map={page:'pages',nav:'nav',stockist:'stockists',partner:'partners',friend:'friends',discount:'discounts'};if(type==='subplan')adminState.subscriptions.plans.push(obj);else adminState[map[type]].push(obj);renderGenericEditors()}
function removeGeneric(type,i){captureAll();const map={page:'pages',nav:'nav',stockist:'stockists',partner:'partners',friend:'friends',discount:'discounts'};if(type==='subplan')adminState.subscriptions.plans.splice(i,1);else adminState[map[type]].splice(i,1);renderGenericEditors()}

function readAssetUpload(input,onDone){const file=input.files?.[0];if(!file)return;const video=file.type.startsWith('video/'),limit=video?1800000:900000;if(file.size>limit){alert(video?'For this static prototype, keep direct video uploads under 1.8 MB. Use an MP4/WebM URL or YouTube link for normal marketing videos.':'Please keep uploaded image/logo/icon files under 900 KB for this browser prototype.');input.value='';return}const r=new FileReader();r.onload=()=>onDone(String(r.result||''));r.readAsDataURL(file)}
function previewShipping(){$('shippingPreview').textContent=Number($('freeShippingThreshold').value||0)>0?`Storefront message: Free HK delivery over ${money($('freeShippingThreshold').value)}`:'Storefront message: Free HK delivery on every order'}

let invoiceLines=[{description:'Custom order',qty:1,price:0}];
function renderInvoiceLines(){$('invoiceLines').innerHTML=invoiceLines.map((l,i)=>`<div class="invoice-line" data-invoice-line="${i}"><input data-k="description" value="${esc(l.description)}" placeholder="Description"><input data-k="qty" type="number" min="1" value="${l.qty}"><input data-k="price" type="number" min="0" value="${l.price}" placeholder="Price"><button class="admin-secondary compact" data-remove-invoice-line="${i}">Remove</button></div>`).join('')}
function saveInvoice(){document.querySelectorAll('[data-invoice-line]').forEach(el=>{const i=+el.dataset.invoiceLine;el.querySelectorAll('[data-k]').forEach(inp=>invoiceLines[i][inp.dataset.k]=inp.type==='number'?Number(inp.value):inp.value)});const subtotal=invoiceLines.reduce((s,l)=>s+l.qty*l.price,0),shipping=Number($('invoiceShipping').value||0),discount=Number($('invoiceDiscount').value||0),total=Math.max(0,subtotal+shipping-discount);const inv={id:'INV-'+String(Date.now()).slice(-8),created:new Date().toISOString(),customer:$('invoiceCustomer').value,email:$('invoiceEmail').value,due:$('invoiceDue').value,reference:$('invoiceRef').value,notes:$('invoiceNotes').value,lines:invoiceLines,subtotal,shipping,discount,total,status:'Unpaid'};const arr=invoices();arr.unshift(inv);localStorage.setItem(ZB_INVOICES,JSON.stringify(arr));const url=new URL('invoice.html',location.href);url.searchParams.set('invoice',inv.id);if(inv.email)logEmailEvent({type:'Customer invoice',to:inv.email,subject:`ZIONBURG invoice ${inv.id}`,invoiceId:inv.id});salesEmailList(adminState).forEach(to=>logEmailEvent({type:'Sales invoice copy',to,subject:`Invoice copy — ${inv.id}`,invoiceId:inv.id}));fetch('/.netlify/functions/send-invoice-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({invoice:inv,url:url.href,event:'created'})}).catch(()=>{});$('invoiceSuccess').innerHTML=`Payment link created:<br><a href="${url.href}" target="_blank">${url.href}</a>`;$('invoiceSuccess').classList.add('show');renderInvoices();renderEmailLog()}
function renderInvoices(){const arr=invoices();$('invoiceTable').innerHTML=arr.map(i=>`<tr><td><strong>${esc(i.id)}</strong></td><td>${esc(i.customer||i.email||'—')}</td><td>${money(i.total)}</td><td>${statusBadge(i.status==='Paid'?'active':'draft')}</td><td><a class="text-button" href="invoice.html?invoice=${encodeURIComponent(i.id)}" target="_blank">Open</a></td></tr>`).join('')||'<tr><td colspan="5" class="empty-cell">No custom invoices yet.</td></tr>'}

function bindEvents(){
  $('saveAdmin').onclick=async()=>{captureAll();saveSite(adminState);const btn=$('saveAdmin'),old=btn.textContent;btn.disabled=true;btn.textContent='Publishing…';try{await ZBSupa.syncSite(adminState);adminState=getSite();renderSales();renderAnalytics();renderSubs();renderEmailLog();showSaveToast()}catch(err){console.error(err);alert('Could not publish to Supabase: '+err.message)}finally{btn.disabled=false;btn.textContent=old}};
  $('loadDemo').onclick=()=>{if(!confirm('Reset the prototype content to the ZB demo defaults?'))return;localStorage.removeItem(ZB_KEY);adminState=getSite();selectedProductId=null;selectedCollectionId=null;selectedInterfaceLocale=null;renderSettings();renderSales();renderAnalytics();renderSubs();renderEmailLog()};
  $('addProduct').onclick=addNewProduct;$('backProducts').onclick=()=>{captureProductEditor();renderProductList()};$('doneProduct').onclick=()=>{captureProductEditor();renderProductList()};
  $('duplicateProduct').onclick=()=>{captureProductEditor();const p=currentProduct();if(!p)return;const copy=JSON.parse(JSON.stringify(p));copy.id=uid('prod');copy.title=`${p.title} copy`;copy.handle=`${p.handle}-copy-${Date.now().toString().slice(-3)}`;copy.status='draft';copy.variants=(copy.variants||[]).map(v=>({...v,id:uid('var')}));adminState.catalogProducts.push(copy);(copy.collectionIds||[]).forEach(cid=>{const c=adminState.collections.find(x=>x.id===cid);if(c){c.productIds=c.productIds||[];c.productIds.push(copy.id)}});openProductEditor(copy.id)};
  $('archiveProduct').onclick=()=>{const p=currentProduct();if(!p)return;p.status=p.status==='archived'?'draft':'archived';$('productStatus').value=p.status;$('archiveProduct').textContent=p.status==='archived'?'Unarchive':'Archive'};
  $('addVariant').onclick=()=>{captureProductEditor();const p=currentProduct();p.variants.push({id:uid('var'),name:'New variant',state:'',price:0,sku:'',color:'#d8d8d8',image:'',inventory:0,active:true});renderVariantEditors()};
  $('addProductMedia').onclick=()=>{captureProductEditor();const p=currentProduct();p.media.push({type:'image',src:'',poster:'',alt:'',autoplay:true,loop:true,controls:false});renderProductMediaEditors()};
  $('addCollection').onclick=addNewCollection;$('backCollections').onclick=()=>{captureCollectionEditor();renderCollectionList()};$('doneCollection').onclick=()=>{captureCollectionEditor();renderCollectionList()};$('deleteCollection').onclick=()=>{const c=currentCollection();if(!c||!confirm(`Delete “${c.title}”?`))return;adminState.collections=adminState.collections.filter(x=>x.id!==c.id);adminState.catalogProducts.forEach(p=>p.collectionIds=(p.collectionIds||[]).filter(id=>id!==c.id));adminState.bundles=adminState.bundles.filter(b=>!(b.scopeType==='collection'&&b.scopeId===c.id));renderCollectionList()};
  $('addMarket').onclick=()=>{captureAll();adminState.markets.items.push({id:uid('market'),name:'New market',countries:['Other'],currency:'USD',symbol:'US$',fxRate:0.128,enabled:false,taxRate:0,shippingFee:0,freeShippingThreshold:0,deliveryEstimate:'5–12 business days'});renderMarketEditors()};
  $('addBundle').onclick=()=>{captureAll();const p=adminState.catalogProducts[0];adminState.bundles.push({id:uid('bundle'),name:'New bundle',qty:3,price:null,badge:'',active:true,scopeType:p?'product':'all',scopeId:p?.id||''});renderBundleEditors()};
  $('addDiscount').onclick=()=>addGeneric('discount',{code:'NEWCODE',type:'percent',value:10,enabled:true});$('addSubPlan').onclick=()=>addGeneric('subplan',{label:'Every 4 weeks',value:'4-weeks'});$('addPage').onclick=()=>addGeneric('page',{title:'New Page',slug:'new-page',body:'Add page content here.'});$('addNav').onclick=()=>addGeneric('nav',{label:'New Link',type:'link',href:'page.html?slug=new-page',visible:true});$('addStockist').onclick=()=>addGeneric('stockist',{name:'New stockist',type:'Physical Store',country:'Hong Kong',region:'',city:'',address:'',url:'',active:true});$('addFooterLink').onclick=()=>{captureAll();adminState.footer=adminState.footer||clone(defaults.footer);adminState.footer.links=adminState.footer.links||[];adminState.footer.links.push({label:'New link',href:'',visible:true});renderFooterLinkEditors()};$('addPartner').onclick=()=>addGeneric('partner',{name:'New partner',type:'Community partner',note:'',image:'',imageFit:'cover',url:''});$('addFriend').onclick=()=>addGeneric('friend',{name:'New friend',type:'Creator',note:'',image:'',imageFit:'cover',url:''});
  $('resetBenefitIcons').onclick=()=>{captureBenefits();const icons=['assets/plant.svg','assets/alcohol-free.svg','assets/vitamin.svg','assets/cooling.svg'];adminState.benefits.forEach((b,i)=>b.icon=icons[i]||b.icon);renderBenefitEditors()};
  $('resetNavLogo').onclick=()=>{adminState.branding.logo='';$('navLogoUrl').value='';renderBrandingPreviews()};$('resetFavicon').onclick=()=>{adminState.branding.favicon='assets/favicon.svg';$('faviconUrl').value='assets/favicon.svg';renderBrandingPreviews()};
  $('freeShippingThreshold').addEventListener('input',previewShipping);$('productSearch').addEventListener('input',renderProductList);$('productStatusFilter').addEventListener('change',renderProductList);
  $('productTitle').addEventListener('input',()=>{if(!$('productHandle').dataset.touched)$('productHandle').value=slugify($('productTitle').value)});$('productHandle').addEventListener('input',()=>$('productHandle').dataset.touched='1');$('collectionTitle').addEventListener('input',()=>{if(!$('collectionHandle').dataset.touched)$('collectionHandle').value=slugify($('collectionTitle').value)});$('collectionHandle').addEventListener('input',()=>$('collectionHandle').dataset.touched='1');
  $('addInvoiceLine').onclick=()=>{invoiceLines.push({description:'',qty:1,price:0});renderInvoiceLines()};$('generateInvoice').onclick=saveInvoice;
  $('shipmentForm').addEventListener('submit',e=>{e.preventDefault();saveShipment()});$('closeShipmentDialog').onclick=closeShipmentDialog;$('cancelShipmentDialog').onclick=closeShipmentDialog;$('shipmentDialog').addEventListener('click',e=>{if(e.target===$('shipmentDialog'))closeShipmentDialog()});

  document.addEventListener('click',e=>{
    const ep=e.target.closest('[data-edit-product]');if(ep){openProductEditor(ep.dataset.editProduct);return}const ec=e.target.closest('[data-edit-collection]');if(ec){openCollectionEditor(ec.dataset.editCollection);return}
    const rv=e.target.closest('[data-remove-variant]');if(rv){captureVariants();const p=currentProduct();p.variants.splice(+rv.dataset.removeVariant,1);renderVariantEditors();return}
    const rm=e.target.closest('[data-remove-product-media]');if(rm){captureProductMedia();const p=currentProduct();p.media.splice(+rm.dataset.removeProductMedia,1);renderProductMediaEditors();return}
    const mv=e.target.closest('[data-move-product-media]');if(mv){captureProductMedia();const p=currentProduct(),i=+mv.dataset.mediaOrderIndex,j=mv.dataset.moveProductMedia==='up'?i-1:i+1;if(j>=0&&j<p.media.length){[p.media[i],p.media[j]]=[p.media[j],p.media[i]];renderProductMediaEditors()}return}
    const rmk=e.target.closest('[data-remove-market]');if(rmk){captureMarketEditors();const i=+rmk.dataset.removeMarket;if(adminState.markets.items[i]?.id!=='hk'){adminState.markets.items.splice(i,1);renderMarketEditors()}return}
    const rb=e.target.closest('[data-remove-bundle]');if(rb){captureBundles();adminState.bundles.splice(+rb.dataset.removeBundle,1);renderBundleEditors();return}
    const rfl=e.target.closest('[data-remove-footer-link]');if(rfl){captureFooterLinks();adminState.footer.links.splice(+rfl.dataset.removeFooterLink,1);renderFooterLinkEditors();return}
    const rg=e.target.closest('[data-remove]');if(rg){const type=rg.dataset.remove,el=rg.closest(`[data-${type}]`);removeGeneric(type,+el.dataset[type]);return}
    const ril=e.target.closest('[data-remove-invoice-line]');if(ril){invoiceLines.splice(+ril.dataset.removeInvoiceLine,1);renderInvoiceLines();return}
    const sh=e.target.closest('[data-ship-order]');if(sh){openShipmentDialog(+sh.dataset.shipOrder);return}
  });
  document.addEventListener('change',e=>{
    if(e.target.id==='interfaceTranslationLocale'){captureInterfaceTranslations(selectedInterfaceLocale);selectedInterfaceLocale=e.target.value;renderInterfaceTranslationEditor();return}
    const cu=e.target.closest('[data-community-upload]');if(cu){const type=cu.dataset.communityUpload,i=+cu.dataset.communityIndex;readAssetUpload(cu,data=>{captureGenericEditors();const key=type==='partner'?'partners':'friends';if(adminState[key]?.[i])adminState[key][i].image=data;renderGenericEditors()});return}
    if(e.target.matches('[data-language-index],#defaultLocale')){captureLanguageSettings();renderLanguageSettings();const p=currentProduct();if(p&&$('productTranslationEditors'))$('productTranslationEditors').innerHTML=translationFieldsHTML(p,'product');const c=currentCollection();if(c&&$('collectionTranslationEditors'))$('collectionTranslationEditors').innerHTML=translationFieldsHTML(c,'collection');return}
    const scope=e.target.closest('[data-bk="scopeType"]');if(scope){captureBundles();const b=scope.closest('[data-bundle]'),obj=adminState.bundles[+b.dataset.bundle];obj.scopeType=scope.value;obj.scopeId=scope.value==='product'?adminState.catalogProducts[0]?.id||'':scope.value==='collection'?adminState.collections[0]?.id||'':'';renderBundleEditors();return}
    const bu=e.target.closest('[data-benefit-upload]');if(bu){const i=+bu.dataset.benefitUpload;readAssetUpload(bu,data=>{captureBenefits();adminState.benefits[i].icon=data;renderBenefitEditors()});return}
    const mu=e.target.closest('[data-media-upload-scope]');if(mu){const scopeName=mu.dataset.mediaUploadScope,i=+mu.dataset.mediaUploadIndex;readAssetUpload(mu,data=>{if(scopeName==='home'){captureHomeMedia();const arr=homeMediaFlat();arr[i].src=data;arr[i].type=mu.files?.[0]?.type.startsWith('video/')?'video':'image';setHomeMediaFlat(arr);renderHomeMediaEditors()}else{captureProductMedia();const p=currentProduct();p.media[i].src=data;p.media[i].type=mu.files?.[0]?.type.startsWith('video/')?'video':'image';renderProductMediaEditors()}});return}
    if(e.target.closest('[data-media-k]')){if(e.target.closest('[data-media-scope="home"]')){captureHomeMedia();renderHomeMediaEditors()}else if(e.target.closest('[data-media-scope="product"]')){captureProductMedia();renderProductMediaEditors()}}
  });
  $('navLogoFile').addEventListener('change',e=>readAssetUpload(e.target,data=>{adminState.branding.logo=data;$('navLogoUrl').value=data;renderBrandingPreviews()}));$('faviconFile').addEventListener('change',e=>readAssetUpload(e.target,data=>{adminState.branding.favicon=data;$('faviconUrl').value=data;renderBrandingPreviews()}));$('navLogoUrl').addEventListener('input',()=>{adminState.branding.logo=$('navLogoUrl').value.trim();renderBrandingPreviews()});$('faviconUrl').addEventListener('input',()=>{adminState.branding.favicon=$('faviconUrl').value.trim()||'assets/favicon.svg';renderBrandingPreviews()});$('navLogoText').addEventListener('input',()=>{adminState.branding.logoText=$('navLogoText').value;renderBrandingPreviews()});
}
function showSaveToast(){let t=document.querySelector('.admin-toast');if(!t){t=document.createElement('div');t.className='admin-toast';document.body.appendChild(t)}t.textContent='Changes saved';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}

document.addEventListener('DOMContentLoaded',async()=>{try{const access=await ZBSupa.requireRole(['admin','editor','sales','fulfilment']);if(!access.ok){location.replace('account.html?admin=1&return=/admin.html');return}await ZBSupa.hydrateSiteCache({force:true});adminState=getSite()}catch(err){console.error(err);alert('Could not connect Admin to Supabase: '+err.message);return}panelNav();renderSales();renderAnalytics();renderSubs();renderSettings();renderInvoiceLines();renderInvoices();renderEmailLog();bindEvents()});
