let applied=null;

function checkoutCountry(){return document.getElementById('country')?.value||currentMarket().countries?.[0]||'Hong Kong'}
function checkoutMarket(){return marketForCountry(checkoutCountry(),getSite())}
function calc(){
  const c=getCart(),sub=cartSubtotal();let disc=0;
  if(applied)disc=applied.type==='percent'?Math.round(sub*Number(applied.value)/100):Number(applied.value||0);
  const after=Math.max(0,sub-disc),country=checkoutCountry(),market=checkoutMarket(),ship=shippingFor(after,country),tax=taxFor(after,ship,country),total=after+ship+tax;
  document.getElementById('checkoutItems').innerHTML=c.length?c.map(i=>`<div class="order-item"><span>${i.name}<br><small>${i.detail||''}</small></span><b>${money(i.price*i.qty,market)}</b></div>`).join(''):`<p>${tr('bagEmpty','Your bag is empty.')}</p>`;
  document.getElementById('coSubtotal').textContent=money(sub,market);document.getElementById('discountRow').style.display=disc?'flex':'none';document.getElementById('coDiscount').textContent='−'+money(disc,market);document.getElementById('coShipping').textContent=ship?money(ship,market):tr('freeDelivery','FREE');document.getElementById('shipPrice').textContent=ship?money(ship,market):tr('freeDelivery','FREE');document.getElementById('coTax').textContent=tax?money(tax,market):money(0,market);document.getElementById('taxRow').style.display=getSite().markets?.taxEngine==='none'?'none':'flex';document.getElementById('coTotal').textContent=money(total,market);
  const estimate=document.getElementById('shipEstimate');if(estimate)estimate.textContent=market.deliveryEstimate||tr('deliveryTiming','Delivery timing shown at checkout');
  return{sub,disc,ship,tax,total,country,market};
}
function renderCheckoutCountries(){
  const site=getSite(),sel=document.getElementById('country');if(!sel)return;const enabled=(site.markets?.items||[]).filter(m=>m.enabled!==false),countries=[];enabled.forEach(m=>(m.countries||[]).forEach(c=>{if(c&&c!=='Other'&&!countries.includes(c))countries.push(c)}));if(enabled.some(m=>(m.countries||[]).includes('Other')))countries.push('Other');sel.innerHTML=countries.map(c=>`<option value="${c}">${c}</option>`).join('');const cm=currentMarket(site),preferred=(cm.countries||[]).find(c=>c!=='Other');if(preferred&&countries.includes(preferred))sel.value=preferred;
}
function renderCheckoutAccount(){const site=getSite(),host=document.getElementById('checkoutAccountNote');if(!host||site.features?.customerAccounts===false){if(host)host.hidden=true;return}const c=currentCustomer();if(c){host.innerHTML=`${tr('signedInAs','Signed in as')} <strong>${c.name||c.email}</strong> · <a href="account.html">${tr('viewAccount','View account')}</a>`;document.getElementById('email').value=c.email||'';const parts=String(c.name||'').trim().split(/\s+/);if(parts[0])document.getElementById('firstName').value=parts[0];if(parts.length>1)document.getElementById('lastName').value=parts.slice(1).join(' ')}else host.innerHTML=`${tr('alreadyAccount','Already have an account?')} <a href="account.html">${tr('signIn','Sign in')}</a> ${currentLocale()==='zh-HK'?'再結帳。':'before checkout.'}`}
function queueOrderEmails(order,site){logEmailEvent({type:'Customer receipt',to:order.email,subject:`Your ZIONBURG receipt — ${order.id}`,orderId:order.id});const recipients=salesEmailList(site);if(site.settings?.sendSalesOrder!==false)recipients.forEach(to=>logEmailEvent({type:'Sales order',to,subject:`New ZIONBURG order ${order.id} — ${baseMoney(order.total)}`,orderId:order.id}));if(site.settings?.sendSalesReceipt!==false)recipients.forEach(to=>logEmailEvent({type:'Receipt / invoice copy',to,subject:`Receipt / invoice copy — ${order.id}`,orderId:order.id}));fetch('/.netlify/functions/send-order-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order,sendSalesOrder:site.settings?.sendSalesOrder!==false,sendSalesReceipt:site.settings?.sendSalesReceipt!==false})}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(()=>{const arr=emailLog();let changed=false;arr.forEach(x=>{if(x.orderId===order.id&&x.status==='Queued (prototype)'){x.status='Sent via Netlify';changed=true}});if(changed)localStorage.setItem(ZB_EMAIL_LOG,JSON.stringify(arr))}).catch(()=>{})}

document.addEventListener('DOMContentLoaded',()=>{
  renderCheckoutCountries();renderCheckoutAccount();calc();
  document.getElementById('country')?.addEventListener('change',()=>{const m=checkoutMarket();setMarket(m.id);calc()});
  document.getElementById('applyDiscount').addEventListener('click',()=>{const code=document.getElementById('discountCode').value.trim().toUpperCase();applied=getSite().discounts.find(d=>d.enabled!==false&&d.code.toUpperCase()===code)||null;document.getElementById('discountMessage').textContent=applied?`${code} ${currentLocale()==='zh-HK'?'已套用。':'applied.'}`:tr('codeNotFound','Code not found.');calc()});
  document.getElementById('checkoutForm').addEventListener('submit',e=>{e.preventDefault();const c=getCart();if(!c.length){alert(tr('bagEmpty','Your bag is empty.'));return}const site=getSite(),t=calc(),os=JSON.parse(localStorage.getItem(ZB_ORDERS)||'[]'),id='ZB-'+String(Date.now()).slice(-7),firstName=document.getElementById('firstName').value,lastName=document.getElementById('lastName').value,email=document.getElementById('email').value.trim().toLowerCase(),account=currentCustomer();const order={id,date:new Date().toISOString(),customer:`${firstName} ${lastName}`.trim(),email,phone:document.getElementById('phone')?.value||'',address:document.getElementById('address')?.value||'',country:t.country,region:document.getElementById('region')?.value||'',postal:document.getElementById('postal')?.value||'',customerAccountId:account&&String(account.email).toLowerCase()===email?account.id||'':'',items:c,subtotal:t.sub,discount:t.disc,discountCode:applied?.code||'',shipping:t.ship,tax:t.tax,total:t.total,marketId:t.market.id,currency:t.market.currency,fxRate:Number(t.market.fxRate||1),displayTotal:Number(t.total||0)*Number(t.market.fxRate||1),payment:'Paid (test)',fulfilment:'Unfulfilled'};os.unshift(order);localStorage.setItem(ZB_ORDERS,JSON.stringify(os));const subs=JSON.parse(localStorage.getItem(ZB_SUBS)||'[]');c.filter(i=>i.subscription).forEach(i=>subs.unshift({id:'SUB-'+Date.now()+Math.random(),status:'Active',email,item:i.name,cadence:i.cadence,amount:i.price,nextBilling:new Date(Date.now()+28*864e5).toISOString()}));localStorage.setItem(ZB_SUBS,JSON.stringify(subs));queueOrderEmails(order,site);saveCart([]);location.href=`invoice.html?order=${encodeURIComponent(id)}`})
});
