document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id),id=new URLSearchParams(location.search).get('id');let list=ZB.customInvoices(),inv=list.find(x=>x.id===id);
 if(!inv){$('customPayRoot').innerHTML='<div class="custom-pay-card"><h1>Invoice not found.</h1></div>';return}
 const money=n=>'HK$'+Number(n||0).toLocaleString();
 $('payInvoiceNumber').textContent=inv.invoiceNumber;$('payDue').textContent=inv.dueAt?'Due '+new Date(inv.dueAt).toLocaleDateString():'';$('payCustomer').textContent=((inv.customer?.firstName||'')+' '+(inv.customer?.lastName||'')).trim();$('payEmail').textContent=inv.customer?.email||'';
 $('payItems').innerHTML=(inv.items||[]).map(i=>`<div class="custom-pay-item"><div><strong>${ZB.esc(i.name)}</strong><small>${Number(i.qty||1)} × HK$${Number(i.price||0).toLocaleString()}</small></div><strong>${money(Number(i.qty||1)*Number(i.price||0))}</strong></div>`).join('');
 $('paySubtotal').textContent=money(inv.subtotal);if(Number(inv.discountAmount||0)>0){$('payDiscountRow').hidden=false;$('payDiscount').textContent='−'+money(inv.discountAmount)}$('payShipping').textContent=inv.shipping?money(inv.shipping):'Free';$('payTotal').textContent=money(inv.total);
 function showStatus(){const paid=inv.status==='paid';$('payStatus').textContent=String(inv.status||'open').toUpperCase();$('payStatus').className='status-pill status-'+(paid?'paid':'pending');$('simulateInvoicePayment').disabled=paid||inv.status==='void';$('simulateInvoicePayment').textContent=paid?'PAID':inv.status==='void'?'INVOICE VOID':'PAY SECURELY WITH STRIPE';$('customPaySuccess').hidden=!paid;$('paidInvoiceLink').href='invoice.html?custom=1&id='+encodeURIComponent(inv.id)}showStatus();
 $('simulateInvoicePayment').onclick=()=>{if(inv.stripeHostedInvoiceUrl&&/^https:\/\//.test(inv.stripeHostedInvoiceUrl)){location.href=inv.stripeHostedInvoiceUrl;return}if(new URLSearchParams(location.search).get('demo')!=='1'){alert('This invoice is not connected to a live Stripe hosted payment URL.');return}list=ZB.customInvoices();const idx=list.findIndex(x=>x.id===inv.id);if(idx<0||list[idx].status!=='open')return;const now=new Date().toISOString();list[idx].status='paid';list[idx].paymentStatus='paid';list[idx].paidAt=now;list[idx].paymentMethod='Demo invoice payment';inv=list[idx];ZB.saveCustomInvoices(list);
  const orders=ZB.orders();if(!orders.some(o=>o.customInvoiceId===inv.id)){const order={id:'ORD-CUSTOM-'+Date.now(),orderNumber:'#C'+String(orders.length+1001),invoiceNumber:inv.invoiceNumber,customInvoiceId:inv.id,source:'custom_invoice',createdAt:now,customer:inv.customer,shippingAddress:inv.shippingAddress,items:inv.items,subtotal:inv.subtotal,discount:inv.discount,discountAmount:inv.discountAmount||0,shipping:inv.shipping,total:inv.total,currency:inv.currency||'HKD',paymentStatus:'paid',fulfillmentStatus:'unfulfilled',paymentMethod:'Demo invoice payment',emailStatus:{customer:'sent',internal:ZB.state().settings.internalEmail?'sent':'needs setup'},internalEmail:ZB.state().settings.internalEmail||''};orders.unshift(order);ZB.saveOrders(orders);ZB.upsertCustomerFromOrder(order);const logs=ZB.emailLog();logs.unshift({time:now,type:'Custom invoice paid receipt',recipient:order.customer.email,orderId:order.id,status:'sent'},{time:now,type:'Internal paid invoice copy',recipient:order.internalEmail||'Not configured',orderId:order.id,status:order.internalEmail?'sent':'needs setup'});ZB.saveEmailLog(logs)}showStatus();};
});
