(function(){
const defaults={
 theme:{bg:'#f4f1eb',text:'#171717'},
 products:[
 {name:'Rose',state:'GLOW',color:'#c75b7a',moment:'Pilates, brunch, getting ready, everyday wellness',descriptor:'Soft • Clean • Elevated',price:88},
 {name:'Amber',state:'GROUND',color:'#c99a3a',moment:'Recovery days, yoga, evening routines, travel',descriptor:'Warm • Calm • Grounded',price:88},
 {name:'Mint',state:'RESET',color:'#3a9e8c',moment:'Post-workout, boxing, running, hot weather',descriptor:'Cool • Crisp • Revived',price:88},
 {name:'Cucumber',state:'REFRESH',color:'#5a9e4a',moment:'Gym, commuting, midday refresh, summer',descriptor:'Fresh • Light • Hydrating-feel',price:88},
 {name:'Lavender',state:'UNWIND',color:'#8b6aaf',moment:'Recovery, stretching, evening, long travel days',descriptor:'Calm • Soft • Restorative',price:88},
 {name:'Orange',state:'ENERGIZE',color:'#e07828',moment:'Morning workouts, cycling, tennis, active days',descriptor:'Bright • Fresh • Uplifting',price:88}
 ],
 catalog:[
 {id:'refreshing-wipes',name:'Refreshing Wipes',target:'product-refreshing-wipes',active:true}
 ],
 nav:[
 {label:'PRODUCTS',target:'products-menu',location:'header'},
 {label:'BUNDLES',target:'home-bundles',location:'header'},
 {label:'ABOUT',target:'custom-about',location:'header'},
 {label:'STOCKISTS',target:'stockists',location:'header'},
 {label:'COMMUNITY',target:'community',location:'header'},
 {label:'PRODUCTS',target:'product-refreshing-wipes',location:'footer'},{label:'STOCKISTS',target:'stockists',location:'footer'},{label:'COMMUNITY',target:'community',location:'footer'}
 ],
 pages:[{id:'about',title:'About ZB',slug:'about',eyebrow:'MOVE • RECOVER • REFRESH • GO',intro:'ZB lives in the space between movement, recovery and whatever comes next.',body:'A premium movement and recovery brand built around easy rituals for active, everyday life.'}],
 stockists:[],partners:[],friends:[],
 bundles:{enabled:true,packOptions:[{id:'single',size:1,price:null,label:'1 Pack',badge:'TRY ONE',enabled:true,mode:'same'},{id:'pack-3',size:3,price:230,label:'3 Pack',badge:'',enabled:true,mode:'both'},{id:'pack-6',size:6,price:420,label:'6 Pack',badge:'',enabled:true,mode:'both'},{id:'pack-12',size:12,price:780,label:'12 Pack',badge:'BEST VALUE',enabled:true,mode:'both'}]},
 media:{gallery:['','',''],ritualType:'image',ritualUrl:'',ritualPoster:'',ritualControls:false},
 ritual:{eyebrow:'BETWEEN SWEAT AND SHOWER',headline:'THE IN-BETWEEN IS THE RITUAL.',body:'Not every reset needs a full routine. ZB is designed for the gap between movement and your next plan — a small, easy refresh that keeps pace with the day.',ctaText:'SHOP BUNDLES →',ctaTarget:'home-bundles',visible:true},
 hero:{eyebrow:'REFRESH ANYWHERE',title:'POST-SWEAT\nRESET',subtitle:'Clean, refreshed skin for whatever’s next.',video:''},
 settings:{internalEmail:'',customerReceiptFromName:'ZB',receiptPrefix:'ZB',currency:'HKD',shippingFee:30,freeShippingThreshold:300,apiBaseUrl:''},
 stripeCatalog:{productId:'',lastSyncedAt:'',prices:{}},
 subscriptionConfig:{enabled:true,label:'Subscribe & save',discountPercent:10,defaultPlanId:'every-4-weeks',plans:[{id:'every-4-weeks',label:'Every 4 weeks',interval:'week',intervalCount:4,enabled:true},{id:'every-6-weeks',label:'Every 6 weeks',interval:'week',intervalCount:6,enabled:true},{id:'every-8-weeks',label:'Every 8 weeks',interval:'week',intervalCount:8,enabled:true}]},
 discounts:[
  {id:'welcome10',code:'WELCOME10',name:'Welcome 10%',type:'percent',value:10,minSpend:0,maxUses:null,active:true}
 ]
};
function clone(x){return JSON.parse(JSON.stringify(x))}
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}}
function write(key,val){localStorage.setItem(key,JSON.stringify(val))}
function state(){const s=read('zbState',clone(defaults));s.products=s.products||clone(defaults.products);s.catalog=(s.catalog||clone(defaults.catalog)).map((x,i)=>({id:x.id||('catalog-'+i),name:x.name||('Product '+(i+1)),target:x.target||'home',external:x.external||'',active:x.active!==false}));s.nav=s.nav||clone(defaults.nav);s.nav=s.nav.map(n=>{if(n.location==='header'&&String(n.label||'').toUpperCase()==='SHOP'&&n.target==='home-shop')return Object.assign({},n,{label:'PRODUCTS',target:'products-menu'});if(n.location==='footer'&&String(n.label||'').toUpperCase()==='SHOP'&&n.target==='home-shop')return Object.assign({},n,{label:'PRODUCTS',target:'product-refreshing-wipes'});return n});s.pages=s.pages||clone(defaults.pages);s.settings=Object.assign({},defaults.settings,s.settings||{});s.stripeCatalog=Object.assign({},clone(defaults.stripeCatalog),s.stripeCatalog||{});s.subscriptionConfig=Object.assign({},clone(defaults.subscriptionConfig),s.subscriptionConfig||{});s.subscriptionConfig.plans=(s.subscriptionConfig.plans&&s.subscriptionConfig.plans.length?s.subscriptionConfig.plans:clone(defaults.subscriptionConfig.plans)).map((x,i)=>({id:x.id||('sub-plan-'+i),label:x.label||('Every '+(x.intervalCount||1)+' '+(x.interval||'month')+(Number(x.intervalCount||1)===1?'':'s')),interval:['day','week','month','year'].includes(x.interval)?x.interval:'month',intervalCount:Math.max(1,Number(x.intervalCount||1)),enabled:x.enabled!==false}));if(!s.subscriptionConfig.plans.some(x=>x.id===s.subscriptionConfig.defaultPlanId&&x.enabled!==false)){const first=s.subscriptionConfig.plans.find(x=>x.enabled!==false);s.subscriptionConfig.defaultPlanId=first?.id||''}s.media=Object.assign({},defaults.media,s.media||{});s.ritual=Object.assign({},defaults.ritual,s.ritual||{});s.hero=Object.assign({},defaults.hero,s.hero||{});s.bundles=Object.assign({},clone(defaults.bundles),s.bundles||{});s.discounts=(s.discounts||clone(defaults.discounts)).map((d,i)=>({id:d.id||('discount-'+i),code:String(d.code||'').toUpperCase(),name:d.name||d.code||('Discount '+(i+1)),type:d.type==='fixed'?'fixed':'percent',value:Number(d.value||0),minSpend:Number(d.minSpend||0),maxUses:d.maxUses===null||d.maxUses===''||d.maxUses===undefined?null:Number(d.maxUses),active:d.active!==false}));s.bundles.packOptions=(s.bundles.packOptions&&s.bundles.packOptions.length?s.bundles.packOptions:clone(defaults.bundles.packOptions)).map((o,i)=>({id:o.id||('bundle-'+i+'-'+Number(o.size||1)),size:Number(o.size||1),price:o.price===null||o.price===''?null:Number(o.price),label:o.label||(Number(o.size||1)+' Pack'),badge:o.badge||'',enabled:o.enabled!==false,mode:o.mode||(Number(o.size||1)===1?'same':(s.bundles.allowSame===false?'mix':s.bundles.allowMix===false?'same':'both'))}));return s}
function saveState(s){write('zbState',s)}
function cart(){return read('zbCart',[])}function saveCart(c){write('zbCart',c)}
function orders(){return read('zbOrders',[])}function saveOrders(o){write('zbOrders',o)}
function customers(){return read('zbCustomers',[])}function saveCustomers(c){write('zbCustomers',c)}
function emailLog(){return read('zbEmailLog',[])}function saveEmailLog(x){write('zbEmailLog',x)}
function subscriptions(){return read('zbSubscriptions',[])}function saveSubscriptions(x){write('zbSubscriptions',x)}
function customInvoices(){return read('zbCustomInvoices',[])}function saveCustomInvoices(x){write('zbCustomInvoices',x)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function hrefFor(target){if(target==='home')return'index.html';if(target==='products-menu')return'product.html';if(target==='product-refreshing-wipes')return'product.html';if(target==='home-shop')return'index.html#shop';if(target==='home-bundles')return'index.html#bundles';if(target==='stockists')return'stockists.html';if(target==='community')return'community.html';if(target&&target.startsWith('custom-'))return'page.html?slug='+encodeURIComponent(target.slice(7));if(target&&target.startsWith('http'))return target;return target||'#'}
function shippingHeadline(s){const t=Math.max(0,Number(s.settings?.freeShippingThreshold||0));return t===0?'FREE HK DELIVERY ON ALL ORDERS':`FREE HK DELIVERY OVER HK$${t}`}
function renderShippingMessaging(){const s=state();const headline=shippingHeadline(s);document.querySelectorAll('[data-shipping-announcement]').forEach(el=>{el.innerHTML=`${esc(headline)} <span>•</span> SHOP BUNDLES & SAVE`})}
function renderNav(){const s=state();const productItems=(s.catalog||[]).filter(x=>x.active!==false);document.querySelectorAll('[data-site-nav]').forEach(el=>{el.innerHTML=s.nav.filter(n=>n.location==='header').map(n=>{if(n.target==='products-menu'){const items=productItems.length?productItems.map(x=>`<a class="nav-product-link" href="${esc(x.external||hrefFor(x.target))}"><span>${esc(x.name)}</span><small>VIEW PRODUCT →</small></a>`).join(''):`<span class="nav-empty">No products published yet.</span>`;return `<div class="nav-dropdown"><button class="nav-dropdown-trigger" type="button" aria-haspopup="true"><span>${esc(n.label||'PRODUCTS')}</span><span class="nav-chevron" aria-hidden="true">⌄</span></button><div class="nav-dropdown-menu">${items}</div></div>`}return `<a href="${esc(hrefFor(n.target))}">${esc(n.label)}</a>`}).join('')});document.querySelectorAll('[data-footer-nav]').forEach(el=>{el.innerHTML=s.nav.filter(n=>n.location==='footer').map(n=>`<a href="${esc(hrefFor(n.target))}">${esc(n.label)}</a>`).join('')});document.documentElement.style.setProperty('--bg',s.theme?.bg||'#f4f1eb');document.documentElement.style.setProperty('--text',s.theme?.text||'#171717');renderShippingMessaging()}
function addToCart(item){const c=cart();if(item.purchaseType==='subscription'){const recurring=c.find(x=>x.purchaseType==='subscription');if(recurring&&recurring.subscription?.planId!==item.subscription?.planId){alert('For a smooth Stripe subscription checkout, recurring items in one bag need the same delivery frequency. Please use '+(recurring.subscription?.label||'the existing frequency')+' or checkout separately.');return}}c.push(Object.assign({qty:1},item));saveCart(c);renderCartUI();openCart()}
function renderCartUI(){const c=cart();document.querySelectorAll('#cartCount').forEach(x=>x.textContent=c.reduce((a,i)=>a+(i.qty||1),0));const items=document.getElementById('cartItems');if(items){items.innerHTML=c.length?c.map((i,idx)=>`<div class="cart-row"><div class="cart-thumb" style="--accent:${esc(i.color||'#ccc')}"></div><div><strong>${esc(i.name)}</strong>${i.purchaseType==='subscription'?`<span class="cart-sub-badge">SUBSCRIPTION · ${esc(i.subscription?.label||'Recurring')}</span>`:''}<small style="display:block;color:#777">${esc(i.meta||'')}</small></div><div>HK$${Number(i.price||0)*(i.qty||1)}<br><button class="danger-link" data-remove-cart="${idx}">remove</button></div></div>`).join(''):'<p>Your bag is empty.</p>';items.querySelectorAll('[data-remove-cart]').forEach(b=>b.onclick=()=>{const c2=cart();c2.splice(Number(b.dataset.removeCart),1);saveCart(c2);renderCartUI()})}const subtotal=c.reduce((a,i)=>a+Number(i.price||0)*(i.qty||1),0);document.querySelectorAll('#subtotal').forEach(x=>x.textContent='HK$'+subtotal);const s=state(),threshold=Math.max(0,Number(s.settings?.freeShippingThreshold||0));document.querySelectorAll('[data-shipping-note]').forEach(x=>{x.textContent=threshold===0?'Free delivery on every order.':subtotal>=threshold?'Free delivery unlocked.':`HK$${Math.max(0,threshold-subtotal)} away from free delivery.`})}
function openCart(){document.getElementById('cartDrawer')?.classList.add('open');document.getElementById('scrim')?.classList.add('show')}
function closeCart(){document.getElementById('cartDrawer')?.classList.remove('open');document.getElementById('scrim')?.classList.remove('show')}
function bindCart(){document.getElementById('cartBtn')?.addEventListener('click',openCart);document.getElementById('closeCart')?.addEventListener('click',closeCart);document.getElementById('scrim')?.addEventListener('click',closeCart);renderCartUI()}
function upsertCustomerFromOrder(order){let list=customers();let c=list.find(x=>x.email.toLowerCase()===order.customer.email.toLowerCase());if(!c){c={id:'CUS-'+Date.now(),email:order.customer.email,firstName:order.customer.firstName,lastName:order.customer.lastName,phone:order.customer.phone||'',createdAt:order.createdAt,orders:0,totalSpend:0,lastOrderAt:order.createdAt,discountsUsed:{}};list.unshift(c)}c.discountsUsed=c.discountsUsed||{};c.orders+=1;c.totalSpend+=order.total;c.lastOrderAt=order.createdAt;c.firstName=order.customer.firstName;c.lastName=order.customer.lastName;c.phone=order.customer.phone||c.phone;if(order.discount?.code)c.discountsUsed[order.discount.code]=(c.discountsUsed[order.discount.code]||0)+1;saveCustomers(list)}
window.ZB={defaults,state,saveState,cart,saveCart,orders,saveOrders,customers,saveCustomers,emailLog,saveEmailLog,subscriptions,saveSubscriptions,customInvoices,saveCustomInvoices,esc,hrefFor,shippingHeadline,renderNav,addToCart,renderCartUI,bindCart,upsertCustomerFromOrder};
document.addEventListener('DOMContentLoaded',()=>{renderNav();bindCart()})
})();
